package com.zero.doplan.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zero.doplan.db.entity.Plan;
import com.zero.doplan.db.entity.Sign;

import com.zero.doplan.greendao.PlanDao;
import com.zero.doplan.greendao.SignDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planDaoConfig;
    private final DaoConfig signDaoConfig;

    private final PlanDao planDao;
    private final SignDao signDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        signDaoConfig = daoConfigMap.get(SignDao.class).clone();
        signDaoConfig.initIdentityScope(type);

        planDao = new PlanDao(planDaoConfig, this);
        signDao = new SignDao(signDaoConfig, this);

        registerDao(Plan.class, planDao);
        registerDao(Sign.class, signDao);
    }
    
    public void clear() {
        planDaoConfig.clearIdentityScope();
        signDaoConfig.clearIdentityScope();
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public SignDao getSignDao() {
        return signDao;
    }

}
