package com.zero.doplan.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.zero.doplan.db.entity.PlanType;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "t_plan_type".
 */
public class PlanTypeDao extends AbstractDao<PlanType, Long> {

    public static final String TABLENAME = "t_plan_type";

    /**
     * Properties of entity PlanType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Name = new Property(2, int.class, "name", false, "NAME");
        public final static Property IconId = new Property(3, String.class, "iconId", false, "ICON_ID");
    }


    public PlanTypeDao(DaoConfig config) {
        super(config);
    }

    public PlanTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_plan_type\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"NAME\" INTEGER NOT NULL ," + // 2: name
                "\"ICON_ID\" TEXT);"); // 3: iconId
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_plan_type\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PlanType entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindLong(3, entity.getName());

        String iconId = entity.getIconId();
        if (iconId != null) {
            stmt.bindString(4, iconId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PlanType entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindLong(3, entity.getName());

        String iconId = entity.getIconId();
        if (iconId != null) {
            stmt.bindString(4, iconId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public PlanType readEntity(Cursor cursor, int offset) {
        PlanType entity = new PlanType( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getInt(offset + 1), // type
                cursor.getInt(offset + 2), // name
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // iconId
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, PlanType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setName(cursor.getInt(offset + 2));
        entity.setIconId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

    @Override
    protected final Long updateKeyAfterInsert(PlanType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(PlanType entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PlanType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
